cloud_provider: "{{ lookup('env', 'CLOUD_PROVIDER') }}"
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
aws_region: "{{ lookup('env', 'AWS_REGION') }}"
