name: shelfapp
description: A Dart REST API with Postgres
version: 1.0.0

environment:
  sdk: '>=3.6.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: ^3.4.8
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  test: ^1.25.14
