- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: yes

# Additional tasks to initialize master or join workers
