name:                haskellapp
version:             0.1.0
github:              "githubuser/Database-conn"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

#extra-source-files:
#- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Database-conn#readme>

dependencies:
- base >= 4.7 && < 5
- network
- time

library:
  source-dirs:
    - src
  exposed-modules:
    - Lib
  dependencies:
    - base >= 4.7 && < 5
    - network
    - time

executables:
  haskellapp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - haskellapp
      - base >= 4.7 && < 5
