- name: Install Minikube
  become: yes
  shell: |
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64
    chmod +x minikube
    mv minikube /usr/local/bin/
  args:
    creates: /usr/local/bin/minikube

- name: Start Minikube
  become: yes
  shell: minikube start --driver=none
  args:
    creates: /etc/kubernetes/admin.conf
