source 'https://rubygems.org'

ruby '3.3.5'

gem 'rails', '~> 7.0.4'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.1.0', require: false

gem "rake", "13.0.6"

gem 'pg', '~> 1.4.4'


## Development environment:
#gem 'listen', '>= 3.0.5', '< 3.2'
gem 'listen', '~> 3.5'
# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring', '~> 3.0.0'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
